#!/bin/bash

set -u

usage_exit() {
        echo "Usage: $0 [-d home-directory] [-u user] [-c command] [tag]" 1>&2
        exit 1
}

option_mount_home=""
option_user="-u user"
command=""

while getopts :d:u:c: OPT
do
    case $OPT in
        d)  option_mount_home="-v $OPTARG:/home/user"
            ;;
        u)  option_user="-u $OPTARG"
            ;;
        c)  command="$OPTARG"
            ;;
        \?) usage_exit
            ;;
    esac
done

shift $((OPTIND - 1))

tag=latest
if [ $# -ge 1 ] ; then
  tag=$1
fi

readonly REPO=kunst1080/x11
readonly CONTAINER=$REPO:$tag

docker run --rm -it --privileged \
	-v /run/udev:/run/udev \
	-v /etc/localtime:/etc/localtime:ro \
	-v /usr/lib/locale/locale-archive:/usr/lib/locale/locale-archive:ro \
	$option_user \
	$option_mount_home \
	$CONTAINER \
	$command

